name: Build and Release Decronymer

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'  # Push events to tags matching v*, e.g., v1.0
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run make
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: decronymer-${{ matrix.os }}
        path: |
          out/make/**/*.exe
          out/make/**/*.dmg
          out/make/**/*.deb
          out/make/**/*.rpm
          out/make/**/*.zip
    
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: ./**/*
        draft: false
        prerelease: false
        generate_release_notes: true